### ISSUE TITLE
Bug: trains with delays show wrong "Departure in: ..."

### ISSUE THREAD

**Issue by BWindey** [Kaya-Sem/commandtrein#14]
When viewing the timetable of a station, some trains are 
> Terminaal te laat

to quote the slogan ("terminally too late" for our English-speaking friends).

When viewing the "Departs in" just under the table, this can show something like "23h 55m", because the train should have started driving 5m ago, but has in reality 8m delay.
The actual "Departs in" should show "3m".

**Comment by Kaya-Sem** [comment]
*sigh*

**Comment by Kaya-Sem** [comment]
- [ ] displayment of relative time should not be absolute, only suggested

`Departure in ~ 5 minutes`

`departure in ±5min`

**Comment by Kaya-Sem** [comment]
fixed with [commit](https://github.com/Kaya-Sem/commandtrein/commit/a74f6e024ff55b6348dce9689856948c6359385d)
