### ISSUE TITLE
Feature request: show more info on hover

### ISSUE THREAD

**Issue by BWindey** [Kaya-Sem/commandtrein#2]
When hovering over a row in the table, it would be nice to have it open a window on the side of the table, or below if there isn't enough horizontal space, that would show some more information. 
This information could include things like:
- Which train to take (what is the endstation?)
- Which stops will the train take
- How is the train composed
- Will you need to change trains somewhere
- ...

I don't know how feasible this is, and if there is a TUI framework already supporting such complex behaviour, but it would be a really nice touch to an already great tool.

**Comment by Kaya-Sem** [comment]
Do you want this change implemented in the connection tables, or in the time/liveboard tables? Or both?

**Comment by BWindey** [comment]
Both would be nice.

For the timetables for a station, it could display the stops the train will take, and estimated arrival times in those stations.

**Comment by Kaya-Sem** [comment]
- [x] show info for connections
- [x] show info for timetable
- [x] dump info on enter connections
- [x] dump info on enter timetable

**Comment by Kaya-Sem** [comment]
- [ ] add relevant data now that foundation is present

**Comment by Kaya-Sem** [comment]
![image](https://github.com/user-attachments/assets/0e76661a-f292-435b-9d58-9ddaaab89614)
