### ISSUE TITLE
Feature request: dump info + quit on pressing enter

### ISSUE THREAD

**Issue by BWindey** [Kaya-Sem/commandtrein#3]
Add detection for 'enter' when viewing routes, so that it will quit by erasing the table and printing out info about the train that was currently selected.

'q' would also quit, but leave the table behind without extra info, or even clear the table.

This info could be the same as proposed in #2

**Comment by Kaya-Sem** [comment]
boilerplate implementation has been added in #5 for timetable connections, where on enter it will dump detailed info.

todo:
- [x] implement in connections
- [ ] prettify
- [ ] add more relevant data

**Comment by Kaya-Sem** [comment]
note to self: only close when changes have actually been pushed to main
